version: '3.8'

services:
  app:
    image: projetudsp38/udsp-38-app:${DOCKER_TAG:-latest}
    container_name: udsp-38-app-${DOCKER_TAG:-latest}
    ports:
      - "${PORT:-3000}:3000"
    restart: always