services:
  app:
    image: projetudsp38/udsp-38-app:test
    container_name: udsp-38-app-test
    ports:
      - "3001:3000"
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - /var/www/test/images:/app/public/images