services:
  app:
    image: projetudsp38/udsp-38-app:latest
    container_name: udsp-38-app-latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /var/www/prod/images:/app/public/images