name: Develop CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  deploy-develop:
    uses: ./.github/workflows/common.yml
    with:
      docker_tag: 'test'
      port: '3001'
      environnement: 'test'
    secrets: inherit