name: Production CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-production:
    uses: ./.github/workflows/common.yml
    with:
      docker_tag: 'latest'
      port: '3000'
      environnement: 'prod'
      database_url_secret: 'DATABASE_PROD_URL'
    secrets: inherit